# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [2]:
# Create a 1-dimensional NumPy array using np.array()



# Create a 2-dimensional NumPy array using np.array()


# Create a 3-dimensional Numpy array using np.array()


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)


In [4]:
# Attributes of 2-dimensional array


In [5]:
# Attributes of 3-dimensional array


In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created


In [7]:
# Create an array of shape (10, 2) with only ones


In [8]:
# Create an array of shape (7, 2, 3) of only zeros


In [9]:
# Create an array within a range of 0 and 100 with step 3


In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)


In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)


In [12]:
# Set the random seed to 42


# Create a random array of numbers between 0 & 10 of size (4, 6)


Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable


# Find the unique numbers in the array you just created


In [14]:
# Find the 0'th index of the latest array you created


In [15]:
# Get the first 2 rows of latest array you created


In [16]:
# Get the first 2 values of the first 2 rows of the latest array


In [17]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables


In [18]:
# Add the two arrays together


In [19]:
# Create another array of ones of shape (5, 3)


In [20]:
# Try add the array of ones and the other most recent array together


When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [21]:
# Create another array of ones of shape (3, 5)


In [22]:
# Subtract the new array of ones from the other most recent array


In [23]:
# Multiply the ones array with the latest array


In [3]:
# Take the latest array to the power of 2 using '**'
a=np.random.randint(1,100,(3,3))
a**2


array([[7396,  441, 4761],
       [1849,    4,  324],
       [   4, 2401, 8649]], dtype=int32)

In [5]:
# Do the same thing with np.square()
np.square(a)


array([[7396,  441, 4761],
       [1849,    4,  324],
       [   4, 2401, 8649]], dtype=int32)

In [12]:
# Find the mean of the latest array using np.mean()
np.mean(a)


np.float64(42.55555555555556)

In [13]:
# Find the maximum of the latest array using np.max()
np.max(a)

np.int32(93)

In [14]:
# Find the minimum of the latest array using np.min()
np.min(a)

np.int32(2)

In [16]:
# Find the standard deviation of the latest array
np.std(a)

np.float64(32.54095235617596)

In [17]:
# Find the variance of the latest array
np.var(a)


np.float64(1058.9135802469136)

In [19]:
# Reshape the latest array to (3, 5, 1)
#cannot reshape to (3,5,1) because first a arrays size is 9 and new shape size is 15 

In [22]:
# Transpose the latest array
a.T


array([[86, 43,  2],
       [21,  2, 49],
       [69, 18, 93]], dtype=int32)

What does the transpose do?

In [25]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
b=np.random.randint(1,10,(3,3))
c=np.random.randint(1,10,(3,2))

In [26]:
# Perform a dot product on the two newest arrays you created
np.dot(b,c)

array([[92, 77],
       [40, 69],
       [58, 95]], dtype=int32)

In [39]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
a=np.random.randint(1,10,(4,3))
b=np.random.randint(1,10,(4,3))

In [29]:
# Perform a dot product on the two newest arrays you created
#np.dot(a,b) it shows error because there should not satsisfy the rule for matrxi multiplication simply dot product is same as a matrxi multiplication

It doesn't work. How would you fix it?

In [41]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
c=a.T
np.dot(c,b)

array([[ 84,  51,  70],
       [106, 101,  91],
       [ 77,  64,  59]], dtype=int32)

In [42]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
d=np.random.randint(0,10,(3,3))
e=np.random.randint(0,10,(3,3))


In [43]:
# Compare the two arrays with '>'
d>e

array([[ True, False, False],
       [False, False,  True],
       [False, False, False]])

What happens when you compare the arrays with `>`?

In [44]:
# Compare the two arrays with '>='
d>=e


array([[ True, False, False],
       [False,  True,  True],
       [False,  True,  True]])

In [46]:
d

array([[7, 1, 3],
       [4, 6, 7],
       [5, 9, 5]], dtype=int32)

In [45]:
# Find which elements of the first array are greater than 7
d[d>7]

array([9], dtype=int32)

In [49]:
e

array([[1, 7, 5],
       [9, 6, 0],
       [8, 9, 5]], dtype=int32)

In [48]:
# Which parts of each array are equal? (try using '==')
d[d==e]


array([6, 9, 5], dtype=int32)

In [52]:
# Sort one of the arrays you just created in ascending order

np.sort(d)

array([[1, 3, 7],
       [4, 6, 7],
       [5, 5, 9]], dtype=int32)

In [57]:
d

array([[7, 1, 3],
       [4, 6, 7],
       [5, 9, 5]], dtype=int32)

In [58]:
# Sort the indexes of one of the arrays you just created
np.argsort(d,axis=0)


array([[1, 0, 0],
       [2, 1, 2],
       [0, 2, 1]])

In [60]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(d,axis=0)

array([0, 2, 1])

In [61]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(d)


np.int64(1)

In [62]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(d,axis=1)

array([0, 2, 1])

In [48]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created



In [49]:
# Create an array of normally distributed random numbers



In [50]:
# Create an array with 10 evenly spaced numbers between 1 and 10
a.linspace(1,1


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.